FROM f0xedb/tos-base:latest


RUN pacman -Syu system-updater ccat lsb-release st ttf-symbola-free neofetch feh ttf-inconsolata xorg-xrdb psmisc tos-base-desktop --noconfirm

# clear the pacman cache
RUN pacman -Sc --noconfirm

# tos version
RUN curl https://raw.githubusercontent.com/ODEX-TOS/tos-live/master/toslive/version-edit.txt > /etc/version

# Background pictures
RUN git clone https://github.com/ODEX-TOS/Pictures.git /root/Pictures

# install configurations
RUN mkdir -p /root/.config/tos
RUN curl https://raw.githubusercontent.com/ODEX-TOS/dotfiles/master/tos/colors.conf > /root/.config/tos/colors.conf
RUN curl https://raw.githubusercontent.com/ODEX-TOS/dotfiles/master/tos/floating.conf > /root/.config/tos/floating.conf
RUN curl https://raw.githubusercontent.com/ODEX-TOS/dotfiles/master/tos/icons.conf > /root/.config/tos/icons.conf
RUN curl https://raw.githubusercontent.com/ODEX-TOS/dotfiles/master/tos/tags.conf > /root/.config/tos/tags.conf


# setup zsh
ENV ZSH_LOAD /home/$user/.oh-my-zsh/load
ENV ZSH_PRELOAD /home/$user/.oh-my-zsh/load/preload
ENV ZSH /home/$user/.oh-my-zsh

RUN curl https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -o install.sh
RUN RUNZSH=no CHSH=no sh install.sh && rm install.sh 
RUN git clone https://github.com/zsh-users/zsh-autosuggestions /root/.oh-my-zsh/custom/plugins/zsh-autosuggestions 
RUN git clone https://github.com/marlonrichert/fast-syntax-highlighting.git /root/.oh-my-zsh/custom/plugins/fast-syntax-highlighting
RUN git clone https://github.com/zsh-users/zsh-completions.git /root/.oh-my-zsh/custom/plugins/zsh-completions 
RUN git clone https://github.com/marlonrichert/zsh-autocomplete.git /root/.oh-my-zsh/custom/plugins/zsh-autocomplete 
RUN git clone https://github.com/ODEX-TOS/zsh-load /root/.oh-my-zsh/load 
RUN curl https://raw.githubusercontent.com/ODEX-TOS/tos-live/master/_tos >/root/.oh-my-zsh/custom/plugins/zsh-completions/src/_tos 
RUN git clone https://github.com/denysdovhan/spaceship-prompt.git /root/.oh-my-zsh/custom/themes/spaceship-prompt 
RUN ln -s /root/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme /root/.oh-my-zsh/custom/themes/spaceship.zsh-theme
RUN curl https://raw.githubusercontent.com/ODEX-TOS/dotfiles/master/.zshrc > /root/.zshrc
RUN touch /root/.profile

# install Xresources
RUN curl https://raw.githubusercontent.com/ODEX-TOS/dotfiles/master/.Xresources > /root/.Xresources

RUN echo -e "off\ntime=1800\nfull=off\nbluetooth=false\n/usr/share/backgrounds/tos/default.png\n" > /root/.config/tos/theme

CMD ["/usr/bin/tde"]
